### ISSUE TITLE
unrealized expectations

### ISSUE THREAD

**Issue by elau7e** [cg-cnu/vscode-selection-extended#1]
1) My text (bold - selected text):
ABRA**CADABRA**ABRA**CADABRA**
2) CTRL+SHIFT+i
3) expectations
**ABRA**CADABRA**ABRA**CADABRA
4) realty
**ABRA**CADABRA**ABRACADABRA** 
5) conclusion
inversion ralated with FIRST ITEM ONLY!!!

**Comment by itimgit** [comment]
does not work with multiline

**Comment by cg-cnu** [comment]
Hey @elaus & @itimgit Sorry for the late reply. I have updated the extension to support multiline.
