### ISSUE TITLE
Inverse selection doesn't work with multiselection

### ISSUE THREAD

**Issue by maximedrouhin** [cg-cnu/vscode-selection-extended#2]
Hi! Try selecting a few areas, then press "Ctrl+Shift+I" (or equivalent on Mac)

![img](https://user-images.githubusercontent.com/52411229/81414723-b266ab80-9147-11ea-8552-5ce37c0a3a0f.gif)

I would not expect the selected area to be just the invert selection of the first area selected, but of all of them !

Could you please fix this ?

**Comment by cg-cnu** [comment]
Hi @maxdr88 I released a new version of the extension with the fix. Let me know if if you are able to test it out. Thanks!

**Comment by maximedrouhin** [comment]
Thank you so much! That's perfect!
